import { NAMESPACE_MODULE } from '../constants';
export const LAYOUT_FUNCION = `${NAMESPACE_MODULE}_LAYOUT`;
export const FETCHING = `${LAYOUT_FUNCION}_FETCHING`;
export const DID_INVALIDATION = `${LAYOUT_FUNCION}_DID_INVALIDATION`;
export const RECEIVE = `${LAYOUT_FUNCION}_RECEIVE`;
export const RESET = `${LAYOUT_FUNCION}_RESET`;

export default {
    LAYOUT_FUNCION,
    FETCHING,
    DID_INVALIDATION,
    RECEIVE,
    RESET,
}
