import { NAMESPACE_MODULE } from '../constants';
export const TASK_FUNCION = `${NAMESPACE_MODULE}_TASK`;

export const FETCHING = `${TASK_FUNCION}_FETCHING`;
export const DID_INVALIDATION = `${TASK_FUNCION}_DID_INVALIDATION`;
export const RECEIVE = `${TASK_FUNCION}_RECEIVE`;
export const RESET = `${TASK_FUNCION}_RESET`;


export const CLAIM_RECEIVE = `${TASK_FUNCION}_CLAIM_RECEIVE`;
export const CLAIM_DID_INVALIDATION = `${TASK_FUNCION}_CLAIM_DID_INVALIDATION`;

export const PATCHING = `${TASK_FUNCION}_PATCHING`;
export const PATCH_FAILED = `${TASK_FUNCION}_PATCH_FAILED`;
export const PATCH_SUCESS = `${TASK_FUNCION}_PATCH_SUCESS`;
export const CHANGE_FIELD = `${TASK_FUNCION}_CHANGE_FIELD`;
export const SAVE_DOC_SUCESS = `${TASK_FUNCION}_SAVE_DOC_SUCESS`;
export const SAVE_DOC_FAILED = `${TASK_FUNCION}_SAVE_DOC_FAILED`;
export const REFER_DATA = `${TASK_FUNCION}_REFER_DATA`;

export default {
    CHANGE_FIELD,
    TASK_FUNCION,
    DID_INVALIDATION,
    FETCHING,
    RECEIVE,
    CLAIM_RECEIVE,
    CLAIM_DID_INVALIDATION,
    RESET,
    PATCHING,
    PATCH_FAILED,
    PATCH_SUCESS,
    SAVE_DOC_SUCESS,
    SAVE_DOC_FAILED,
    REFER_DATA
}