export const REWORK_BATCH_REQUEST_MULTIPLE_TASK = 'REWORK_BATCH_REQUEST_MULTIPLE_TASK';
export const REWORK_BATCH_RESPONSE_MULTIPLE_TASK = 'REWORK_BATCH_RESPONSE_MULTIPLE_TASK';
export const REWORK_BATCH_SAVING_MULTIPLE_TASK = 'REWORK_BATCH_SAVING_MULTIPLE_TASK';
export const REWORK_BATCH_SAVED_SUCCESS_MULTIPLE_TASK = 'REWORK_BATCH_SAVED_SUCCESS_MULTIPLE_TASK';
export const REWORK_BATCH_SAVED_ERROR_MULTIPLE_TASK = 'REWORK_BATCH_SAVED_ERROR_MULTIPLE_TASK';
export const REWORK_BATCH_RESET_STATE_MULTIPLE_TASK = 'REWORK_BATCH_RESET_STATE_MULTIPLE_TASK';
export const REWORK_BATCH_MULTIPLE_CLOSE_SNACKBAR = 'REWORK_BATCH_MULTIPLE_CLOSE_SNACKBAR';
export const REWORK_BATCH_MULTIPLE_SHOW_SNACKBAR = 'REWORK_BATCH_MULTIPLE_SHOW_SNACKBAR';
export const REWORK_BATCH_MULTIPLE_SELECT_INDEX_BATCH = 'REWORK_BATCH_MULTIPLE_SELECT_INDEX_BATCH';

export const REWORK_BATCH_SHOW_DETAIL_BATCH = 'REWORK_BATCH_SHOW_DETAIL_BATCH';
export const REWORK_BATCH_REQUEST_DETAIL = 'REWORK_BATCH_REQUEST_DETAIL';
export const REWORK_BATCH_RESPONSE_DETAIL = 'REWORK_BATCH_RESPONSE_DETAIL';
export const REWORK_BATCH_SHOW_DIALOG = 'REWORK_BATCH_SHOW_DIALOG';
export const REWORK_BATCH_HIDDE_DIALOG = 'REWORK_BATCH_HIDDE_DIALOG';
export const REWORK_BATCH_RESET = 'REWORK_BATCH_RESET';
