export const OMR_GET_DONE_DATA_DEFINITION = "OMR_GET_DONE_DATA_DEFINITION";
export const OMR_REQUEST_TASK = "OMR_REQUEST_TASK";
export const OMR_RESPONSE_TASK = "OMR_RESPONSE_TASK";

export const OMR_SHOW_SNACKBAR = "OMR_SHOW_SNACKBAR";
export const OMR_SAVING_TASK = "OMR_SAVING_TASK";
export const OMR_SAVED_SUCCESS_TASK = "OMR_SAVED_SUCCESS_TASK";
export const OMR_SAVED_ERROR_TASK = "OMR_SAVED_ERROR_TASK";
export const OMR_RESET_STATE_TASK = "OMR_RESET_STATE_TASK";
export const OMR_UPDATE_NEXT_TASK = "OMR_UPDATE_NEXT_TASK";
export const OMR_CLOSE_SNACKBAR = "OMR_CLOSE_SNACKBAR";