export const SET_VALIDATION_LAYOUT_VALUE = '@@FORM/SET_VALIDATION_LAYOUT_VALUE'
export const CHANGING_DATA_FIELD_FROM = '@@FORM/CHANGING_DATA_FIELD_FROM'
export const CHANGE_DATA_FIELD_FROM = '@@FORM/CHANGE_DATA_FIELD_FROM'
export const ON_FOCUS_FIELD_FROM = '@@FORM/ON_FOCUS_FIELD_FROM';
export const SET_VALIDATION_LAYOUT = '@@FORM/SET_VALIDATION_LAYOUT';
export const SET_VALIDATION_FIELD = '@@FORM/SET_VALIDATION_FIELD';
export const SET_VALIDATION_FIELD_VALUE = '@@FORM/SET_VALIDATION_FIELD_VALUE';
export const ON_NEXT_FIELD = '@@FORM/ON_NEXT_FIELD';
export const ON_BLUR_FIELD_FROM = '@@FORM/ON_BLUR_FIELD_FROM'
export const CHANGE_NEXT_FROM = '@@FORM/CHANGE_NEXT_FROM'
export const FOCUS_FIELD_ERROR_FROM = '@@FORM/FOCUS_FIELD_ERROR_FROM';
export const INIT_FIELD_ELEMENT_DATA_FROM = '@@FORM/INIT_FIELD_ELEMENT_DATA_FROM';
export const INIT_DATA = '@@FORM/INIT_DATA'
export const SET_SECTION_FORM = '@@FORM/SET_SECTION_FORM'
export const CHANGE_STATE_FROM = '@@FORM/CHANGE_STATE_FROM'
export const ADD_RECORD = '@@FORM/ADD_RECORD';
export const REMOVE_RECORD = '@@FORM/REMOVE_RECORD';
export const IGNORE_WARNING_FROM = '@@FORM/IGNORE_WARNING_FROM'
export const SHOW_WARNING_FROM = '@@FORM/SHOW_WARNING_FROM'
export const HIDE_WARNING_FROM = '@@FORM/HIDE_WARNING_FROM'
export const FORCUS_FIRST_FROM = '@@FORM/FORCUS_FIRST_FROM'
export const UPDATE_CURRENT_DATA_FROM = '@@FORM/UPDATE_CURRENT_DATA_FROM'
export const ADD_RECORD_SECTION = '@@FORM/ADD_RECORD_SECTION';
export const REMOVE_RECORD_SECTION = '@@FORM/REMOVE_RECORD_SECTION';
export const SWITCH_RECORD_SECTION = '@@FORM/SWITCH_RECORD_SECTION';
export const LOAD_DATA_FROM = '@@FORM/LOAD_DATA_FROM'
export const RESET = '@@FORM/RESET'
export const CLEAR_DATA = '@@FORM/CLEAR_DATA'
export const SET_DISABLE_FIELD = '@@FORM/SET_DISABLE_FIELD'



