export const colors = {
    error: "#ff8c00 ",
    no_error: "#1e90ff",
    focus: "#faebd7",
    default: "white"
}
/**field info */
export const VERIFY_QC_FORM_LIST_FIELD_REQUEST = 'VERIFY_QC_FORM_LIST_FIELD_REQUEST';
export const VERIFY_QC_FORM_LIST_FIELD_RECEIVE_DATAS = 'VERIFY_QC_FORM_LIST_FIELD_RECEIVE_DATAS';
/**records */
export const VERIFY_QC_FORM_LIST_RECORD_REQUEST = 'VERIFY_QC_FORM_LIST_RECORD_REQUEST';
export const VERIFY_QC_FORM_LIST_RECORD_RECEIVE_DATAS = 'VERIFY_QC_FORM_LIST_RECORD_RECEIVE_DATAS';
export const VERIFY_QC_FORM_MODIFY_DATA = 'VERIFY_QC_FORM_MODIFY_DATA';
export const VERIFY_QC_RECORD_UPDATE_ERRORS = "VERIFY_QC_RECORD_UPDATE_ERRORS";

/**errors */
export const VERIFY_QC_ERROR_LIST_REQUEST = 'VERIFY_QC_ERROR_LIST_REQUEST';
export const VERIFY_QC_ERROR_LIST_RECEIVE_DATAS = 'VERIFY_QC_ERROR_LIST_RECEIVE_DATAS';
export const VERIFY_QC_ERROR_OPEN_DIALOG = 'VERIFY_QC_ERROR_OPEN_DIALOG';
export const VERIFY_QC_ERROR_CLOSE_DIALOG = 'VERIFY_QC_ERROR_CLOSE_DIALOG';
export const VERIFY_QC_ERROR_SELECT_ITEM = 'VERIFY_QC_ERROR_SELECT_ITEM';
export const VERIFY_QC_ERROR_REMOVE_ITEM = 'VERIFY_QC_ERROR_REMOVE_ITEM';


/**field */
export const VERIFY_QC_FIELD_FOCUS_WAITING = 'VERIFY_QC_FIELD_FOCUS_WAITING';
export const VERIFY_QC_FIELD_FOCUS = 'VERIFY_QC_FIELD_FOCUS';
export const VERIFY_QC_FIELD_FOCUS_REMOVE = 'VERIFY_QC_FIELD_FOCUS_REMOVE';
export const VERIFY_QC_FIELD_MODIFY = 'VERIFY_QC_FIELD_MODIFY';
export const VERIFY_QC_FIELD_MODIFY_COMPLETE = 'VERIFY_QC_FIELD_MODIFY_COMPLETE';
export const VERIFY_QC_FIELD_ADD_REFS = 'VERIFY_QC_FIELD_ADD_REFS';


/**validation */
export const VERIFY_QC_VALIDATION_GET_LIST_REQUEST = 'VERIFY_QC_VALIDATION_GET_LIST_REQUEST';
export const VERIFY_QC_VALIDATION_GET_LIST_RECEIVE_DATAS = 'VERIFY_QC_VALIDATION_GET_LIST_RECEIVE_DATAS';
export const VERIFY_QC_VALIDATION_VALIDATE_ITEM = 'VERIFY_QC_VALIDATION_VALIDATE_ITEM';

export const VERIFY_QC_KEY_ERROR = 'Error';

export const VERIFY_QC_KEY_LAYOUT_NAME = 'layout_name';

export const VERIFY_QC_KEY_DATA = 'data';

export const VERIFY_QC_KEY_FIELD_QCED = 'field_qced';

/** pre data */
export const VERIFY_QC_LIST_FIELD_VERIFY_QC_CONFIG_RECEIVE = 'VERIFY_QC_LIST_FIELD_VERIFY_QC_CONFIG_RECEIVE';
export const VERIFY_QC_PRE_DATA_LIST_FIELD_REQUEST = 'VERIFY_QC_PRE_DATA_LIST_FIELD_REQUEST';
export const VERIFY_QC_PRE_DATA_LIST_FIELD_RECEIVE_DATAS = 'VERIFY_QC_PRE_DATA_LIST_FIELD_RECEIVE_DATAS';

export const VERIFY_QC_PRE_DATA_LIST_SECTION_REQUEST = 'VERIFY_QC_PRE_DATA_LIST_SECTION_REQUEST';
export const VERIFY_QC_PRE_DATA_LIST_SECTION_RECEIVE_DATAS = 'VERIFY_QC_PRE_DATA_LIST_SECTION_RECEIVE_DATAS';

export const VERIFY_QC_MAX_SIZE = 1;

export const VERIFY_QC_REQUEST_TASK_DATA = "VERIFY_QC_REQUEST_TASK_DATA";

export const VERIFY_QC_RECEIVE_TASK_DATA = "VERIFY_QC_RECEIVE_TASK_DATA";


export const VERIFY_QC_RECEIVE_DATAS = "VERIFY_QC_RECEIVE_DATAS";

export const VERIFY_QC_SAVING_MULTIPLE_TASK = "VERIFY_QC_SAVING_MULTIPLE_TASK";
export const VERIFY_QC_SAVED_SUCCESS_MULTIPLE_TASK = "VERIFY_QC_SAVED_SUCCESS_MULTIPLE_TASK";
export const VERIFY_QC_SAVED_ERROR_MULTIPLE_TASK = "VERIFY_QC_SAVED_ERROR_MULTIPLE_TASK";

export const VERIFY_QC_MULTIPLE_UPDATE_NEXT_TASK = "VERIFY_QC_MULTIPLE_UPDATE_NEXT_TASK";

export const VERIFY_QC_MULTIPLE_RECORD_INFO_DOC_NAME = "doc_name";

export const VERIFY_QC_MULTIPLE_BUTTON_RESET_STATE = "VERIFY_QC_MULTIPLE_BUTTON_RESET_STATE";
export const VERIFY_QC_MULTIPLE_FIELD_RESET_STATE = "VERIFY_QC_MULTIPLE_FIELD_RESET_STATE";
export const VERIFY_QC_MULTIPLE_FORM_RESET_STATE = "VERIFY_QC_MULTIPLE_FORM_RESET_STATE";
export const VERIFY_QC_MULTIPLE_DATA_RESET_STATE = "VERIFY_QC_MULTIPLE_DATA_RESET_STATE";
export const VERIFY_QC_MULTIPLE_IMAGE_RESET_STATE = "VERIFY_QC_MULTIPLE_IMAGE_RESET_STATE";
export const VERIFY_QC_MULTIPLE_IMAGE_SET_DATA = "VERIFY_QC_MULTIPLE_IMAGE_SET_DATA";


export const VERIFY_QC_KEY_WORKFLOW_DATA_RECORD_INDEXS = "indexs";

export const VERIFY_QC_KEY_INPUT_RECORD_INDEX = "record_index";


