export const PENDING = "@@DS/PRODUCTIONS/PROJECT_GUIDE_VIEW_PENDING";
export const ERROR = "@@DS/PRODUCTIONS/PROJECT_GUIDE_VIEW_ERROR";
export const SUCCESS = "@@DS/PRODUCTIONS/PROJECT_GUIDE_VIEW_SUCCESS";
export const RESET = "@@DS/PRODUCTIONS/PROJECT_GUIDE_VIEW_RESET";
export const RESET_ALL = "@@DS/PRODUCTIONS/PROJECT_GUIDE_VIEW_RESET_ALL";
export const PROJECT_GUIDE_VIEW_GET_DATA = "@@DS/PRODUCTIONS/PROJECT_GUIDE_VIEW_GET_DATA";