import {
    PROJECT_FUNCTIONS,
    REMAIN_HUMAN_TASK,
    REMAIN_DOCUMENT,
    USER_TASKS,
    PROJECTS_TASKS_ASSIGINED,
    KEYING_TASK,
    SECTION,
    group,
    project,
    announcement,
    user,
    task,
    task_info,
    user_role_management,
    users,
    section,
    remainHumanTask,
    projectFunction,
    remainDocument,
    userTasks,
    projectsTasksAssigned,
    keying_task,
    documents,
    user_working_detail,
    rework_details,
    document_pause,
    user_task_info
} from './resources'
export default {
    group,
    project,
    user,
    users,
    task_info,
    user_role_management,
    task,
    document_pause,
    announcement,
    [PROJECT_FUNCTIONS]: projectFunction,
    [REMAIN_HUMAN_TASK]: remainHumanTask,
    [REMAIN_DOCUMENT]: remainDocument,
    [USER_TASKS]: userTasks,
    [PROJECTS_TASKS_ASSIGINED]: projectsTasksAssigned,
    [KEYING_TASK]: keying_task,
    [SECTION]: section,
    documents: documents,
    user_working_detail,
    rework_details,
    user_task_info
};