import {
    NAMESPACE_MODULE
} from '../constants';
export const TASK_FUNCION = `${NAMESPACE_MODULE}_TASK`;

export const FETCHING = `${TASK_FUNCION}_FETCHING`;
export const DID_INVALIDATION = `${TASK_FUNCION}_DID_INVALIDATION`;
export const RECEIVE = `${TASK_FUNCION}_RECEIVE`;
export const RESET = `${TASK_FUNCION}_RESET`;


export const CLAIM_RECEIVE = `${TASK_FUNCION}_CLAIM_RECEIVE`;
export const CLAIM_DID_INVALIDATION = `${TASK_FUNCION}_CLAIM_DID_INVALIDATION`;

export const PATCHING = `${TASK_FUNCION}_PATCHING`;
export const PATCH_FAILED = `${TASK_FUNCION}_PATCH_FAILED`;
export const PATCH_SUCESS = `${TASK_FUNCION}_PATCH_SUCESS`;
export const CHANGE_FIELD = `${TASK_FUNCION}_CHANGE_FIELD`;
export const SAVE_DOC_SUCESS = `${TASK_FUNCION}_SAVE_DOC_SUCESS`;
export const SAVE_DOC_FAILED = `${TASK_FUNCION}_SAVE_DOC_FAILED`;
export const REFER_DATA = `${TASK_FUNCION}_REFER_DATA`;
export const INIT_RECORD = `${TASK_FUNCION}_INIT_RECORD`;
export const SELECT_RECORD = `${TASK_FUNCION}_SELECT_RECORD`;
export const UPDATE_RECORD = `${TASK_FUNCION}_UPDATE_RECORD`;
export const SET_DATA_RECORD = `${TASK_FUNCION}_SET_DATA_RECORD`;
export const NEXT_RECORD_WAITING = `${TASK_FUNCION}_NEXT_RECORD_WAITING`;
export const SWITCHING_RECORD = `${TASK_FUNCION}_SWITCHING_RECORD`;
export const INSERT_RECORD = `${TASK_FUNCION}_INSERT_RECORD`;
export const REMOVE_RECORD = `${TASK_FUNCION}_REMOVE_RECORD`;
export const INSERTING_RECORD = `${TASK_FUNCION}_INSERTING_RECORD`;
export const REMOVING_RECORD = `${TASK_FUNCION}_REMOVING_RECORD`;
export const CHANGE_MASK = `${TASK_FUNCION}_CHANGE_MASK`;

export default {
    CHANGE_MASK,
    INSERT_RECORD,
    REMOVE_RECORD,
    INSERTING_RECORD,
    REMOVING_RECORD,
    NEXT_RECORD_WAITING,
    SWITCHING_RECORD,
    SET_DATA_RECORD,
    UPDATE_RECORD,
    INIT_RECORD,
    SELECT_RECORD,
    CHANGE_FIELD,
    TASK_FUNCION,
    DID_INVALIDATION,
    FETCHING,
    RECEIVE,
    CLAIM_RECEIVE,
    CLAIM_DID_INVALIDATION,
    RESET,
    PATCHING,
    PATCH_FAILED,
    PATCH_SUCESS,
    SAVE_DOC_SUCESS,
    SAVE_DOC_FAILED,
    REFER_DATA
}