export const COMPONENT_TEXTFIELD = 'TEXTFIELD';
export const COMPONENT_COMBOBOX = 'COMBOBOX';
export const COMPONENT_CHECKBOX = 'CHECKBOX';
export const COMPONENT_RADIO = 'RADIOBUTTON';
export const COMPONENT_TEXTAREA = 'TEXTAREA';