/**
 * AJAX ACTION DEFINITION
 */

export const PATTERN_ITEM_SHOW_DIALOG = 'PATTERN_ITEM_SHOW_DIALOG';
export const PATTERN_ITEM_HIDE_DIALOG = 'PATTERN_ITEM_HIDE_DIALOG';


/**
 * PARAMETER ITEM
 */
export const KEY_PATTERN_NAME = 'name';
export const KEY_PATTERN_PREVIEW = 'pattern_preview';
export const KEY_PATTERN_CONTENT = 'content';
export const KEY_PATTERN_DESCRIPTION = 'description';
export const KEY_PATTERN_ID = 'id';

/**
 * PATTERN LIST
 */
export const PATTERN_LIST_REQUEST = 'PATTERN_LIST_REQUEST';
export const PATTERN_LIST_RESET_DATA = 'PATTERN_LIST_RESET_DATA';
export const PATTERN_LIST_SET_DATAS = 'PATTERN_LIST_SET_DATAS';
export const PATTERN_LIST_REMOVE_DATA_FROM_LIST =
  'PATTERN_LIST_REMOVE_DATA_FROM_LIST';

/**
 * PATTERN ITEM ACTION
 */
export const PATTERN_ITEM_REQUEST = 'PATTERN_ITEM_REQUEST';
export const PATTERN_ITEM_RESPONSE = 'PATTERN_ITEM_RESPONSE';
export const PATTERN_ITEM_INSERT_DATA = 'PATTERN_ITEM_INSERT_DATA';
export const PATTERN_ITEM_MODIFY_DATA = 'PATTERN_ITEM_MODIFY_DATA';
export const PATTERN_ITEM_ERROR_DATA = 'PATTERN_ITEM_ERROR_DATA';
export const PATTERN_ITEM_HIDE_CONFIRM_DELETE = 'PATTERN_ITEM_HIDE_CONFIRM_DELETE';
export const PATTERN_ITEM_SHOW_CONFIRM_DELETE = 'PATTERN_ITEM_SHOW_CONFIRM_DELETE';
export const PATTERN_ITEM_RESET = 'PATTERN_ITEM_RESET';
export const PATTERN_ITEM_CREATE_EMPTY_DATA = 'PATTERN_ITEM_CREATE_EMPTY_DATA'
export const PATTERN_ITEM_VALIDATED = 'PATTERN_ITEM_VALIDATED'
