/**
 * AJAX ACTION DEFINITION
 */

export const TRANSFORM_RULE_ITEM_SET_DIALOG = 'TRANSFORM_RULE_ITEM_SET_DIALOG';

/**
 * PARAMETER ITEM
 */

export const KEY_TRANSFORM_RULE_NAME = 'name';
export const KEY_TRANSFORM_RULE_PREVIEW = 'transform_rule_preview';
export const KEY_TRANSFORM_RULE_SCRIPT = 'content';
export const KEY_TRANSFORM_RULE_ARGUMENTS = 'arguments';

/**
 * TRANSFORM_RULE LIST
 */
export const TRANSFORM_RULE_LIST_REQUEST = 'TRANSFORM_RULE_LIST_REQUEST';
export const TRANSFORM_RULE_LIST_RESET_DATA = 'TRANSFORM_RULE_LIST_RESET_DATA';
export const TRANSFORM_RULE_LIST_RESPONSE = 'TRANSFORM_RULE_LIST_RESPONSE';

/**
 * TRANSFORM_RULE ITEM ACTION
 */
export const TRANSFORM_RULE_ITEM_REQUEST = 'TRANSFORM_RULE_ITEM_REQUEST';
export const TRANSFORM_RULE_ITEM_RESPONSE = 'TRANSFORM_RULE_ITEM_RESPONSE';
export const TRANSFORM_RULE_ITEM_ERROR_DATA = 'TRANSFORM_RULE_ITEM_ERROR_DATA';

export const TRANSFORM_RULE_ITEM_CREATE_EMPTY_DATA = 'TRANSFORM_RULE_ITEM_CREATE_EMPTY_DATA';

export const TRANSFORM_RULE_ITEM_SHOW_DIALOG = 'TRANSFORM_RULE_ITEM_SHOW_DIALOG';
export const TRANSFORM_RULE_ITEM_HIDE_DIALOG = 'TRANSFORM_RULE_ITEM_HIDE_DIALOG';

export const TRANSFORM_RULE_ITEM_MODIFY_DATA = 'TRANSFORM_RULE_ITEM_MODIFY_DATA';
export const TRANSFORM_RULE_ITEM_TRANSFORM_RULE = 'TRANSFORM_RULE_ITEM_TRANSFORM_RULE';

export const TRANSFORM_RULE_ITEM_RESET = 'TRANSFORM_RULE_ITEM_RESET';
