/**
 * AJAX ACTION DEFINITION
 */

export const VALIDATION_ITEM_SET_DIALOG = 'VALIDATION_ITEM_SET_DIALOG';

/**
 * PARAMETER ITEM
 */

export const KEY_VALIDATION_NAME = 'name';
export const KEY_VALIDATION_PREVIEW = 'validation_preview';
export const KEY_VALIDATION_APPLY_IN_LAYOUT = 'apply_in_layout';
export const KEY_VALIDATION_SCRIPT = 'content';
export const KEY_VALIDATION_ARGUMENTS = 'arguments';

/**
 * VALIDATION LIST
 */
export const VALIDATION_LIST_REQUEST = 'VALIDATION_LIST_REQUEST';
export const VALIDATION_LIST_RESET_DATA = 'VALIDATION_LIST_RESET_DATA';
export const VALIDATION_LIST_RESPONSE = 'VALIDATION_LIST_RESPONSE';

/**
 * VALIDATION ITEM ACTION
 */
export const VALIDATION_ITEM_REQUEST = 'VALIDATION_ITEM_REQUEST';
export const VALIDATION_ITEM_RESPONSE = 'VALIDATION_ITEM_RESPONSE';
export const VALIDATION_ITEM_ERROR_DATA = 'VALIDATION_ITEM_ERROR_DATA';

export const VALIDATION_ITEM_CREATE_EMPTY_DATA =
  'VALIDATION_ITEM_CREATE_EMPTY_DATA';

export const VALIDATION_ITEM_SHOW_DIALOG = 'VALIDATION_ITEM_SHOW_DIALOG';
export const VALIDATION_ITEM_HIDE_DIALOG = 'VALIDATION_ITEM_HIDE_DIALOG';

export const VALIDATION_ITEM_MODIFY_DATA = 'VALIDATION_ITEM_MODIFY_DATA';
export const VALIDATION_ITEM_VALIDATION = 'VALIDATION_ITEM_VALIDATION';

export const VALIDATION_ITEM_RESET = 'VALIDATION_ITEM_RESET';
/**
 * VALIDATION TYPE
 */
export const VALIDATION_TYPE_ERROR = 'error';
export const VALIDATION_TYPE_WARNING = 'warning';
