/**
 * TASK
 */
export const VERIFY_HOLD_RECEIVE_ERROR = 'VERIFY_HOLD_RECEIVE_ERROR';
export const VERIFY_HOLD_RECEIVE_TASKS = 'VERIFY_HOLD_RECEIVE_TASKS';
export const VERIFY_HOLD_REQUEST_TASKS = 'VERIFY_HOLD_REQUEST_TASKS';

export const VERIFY_HOLD_RESET_STATE = 'VERIFY_HOLD_RESET_STATE';
export const VERIFY_HOLD_SAVE_FAILURE = 'VERIFY_HOLD_SAVE_FAILURE';
export const VERIFY_HOLD_SAVE_SUCCESS = 'VERIFY_HOLD_SAVE_SUCCESS';
export const VERIFY_HOLD_SAVING_TASK = 'VERIFY_HOLD_SAVING_TASK';
export const VERIFY_HOLD_SELECT_TASK = 'VERIFY_HOLD_SELECT_TASK';

export const VERIFY_HOLD_KEY_WORKFLOW_LAYOUT_NAME = 'layout_name';
export const VERIFY_HOLD_KEY_WORKFLOW_SECTION_NAME = 'section_name';
/**
 * TASK
 */
export const VERIFY_HOLD_UPDATE_NEXT_TASK = 'VERIFY_HOLD_UPDATE_NEXT_TASK';

/**
 * KEY WORD
 */
export const VERIFY_HOLD_KEY_WORKFLOW_COMPLETE_REASON = 'complete_reason';
export const VERIFY_HOLD_KEY_WORKFLOW_HOLD_DATA = 'hold_data';
export const VERIFY_HOLD_KEY_WORKFLOW_INPUT_DATA = 'input_data';
export const VERIFY_HOLD_KEY_WORKFLOW_KEY_DATAS = 'key_datas';
export const VERIFY_HOLD_KEY_WORKFLOW_VALUE = 'value';
/**
 * TASK ITEM
 */
export const VERIFY_HOLD_MODIFY_TASK = 'VERIFY_HOLD_MODIFY_TASK';
export const VERIFY_HOLD_VALIDATE_ERROR = 'VERIFY_HOLD_VALIDATE_ERROR';
