export const DATA_VIEWER_SELECT_BATCH = 'DATA_VIEWER_SELECT_BATCH';
export const DATA_VIEWER_SELECT_STEP = 'DATA_VIEWER_SELECT_STEP';
export const DATA_VIEWER_REQUEST_BATCHES = 'DATA_VIEWER_REQUEST_BATCHES';
export const DATA_VIEWER_RECIEVE_BATCHES = 'DATA_VIEWER_RECIEVE_BATCHES';
export const DATA_VIEWER_RECIEVE_BATCHES_ERROR =
  'DATA_VIEWER_RECIEVE_BATCHES_ERROR';

export const DATA_VIEWER_REQUEST_LAYOUTS = 'DATA_VIEWER_REQUEST_LAYOUTS';
export const DATA_VIEWER_RECIEVE_LAYOUTS = 'DATA_VIEWER_RECIEVE_LAYOUTS';

export const DATA_VIEWER_REQUEST_TASK = 'DATA_VIEWER_REQUEST_TASK';
export const DATA_VIEWER_RECIEVE_TASKS = 'DATA_VIEWER_RECIEVE_TASKS';
export const DATA_VIEWER_RECIEVE_TASKS_ERROR =
  'DATA_VIEWER_RECIEVE_TASKS_ERROR';

export const DATA_VIEWER_OPEN_IMAGE_VIEWER = 'DATA_VIEWER_OPEN_IMAGE_VIEWER';

export const DATA_VIEWER_RESET_BATCHES = 'DATA_VIEWER_RESET_BATCHES';
export const DATA_VIEWER_RESET_TASKS = 'DATA_VIEWER_RESET_TASKS';
export const DATA_VIEWER_RESET_LAYOUTS = 'DATA_VIEWER_RESET_LAYOUTS';
