export const GROUP_IMAGES_GET_TASK = "GROUP_IMAGES_GET_TASK";
export const GROUP_IMAGES_SET_TASK = "GROUP_IMAGES_SET_TASK";

export const GROUP_IMAGES_CHANGE_NEXT = "GROUP_IMAGES_CHANGE_NEXT";

export const GROUP_IMAGES_CHECK_IMAGE = "GROUP_IMAGES_CHECK_IMAGE";
export const GROUP_IMAGES_SELECT_REASON = "GROUP_IMAGES_SELECT_REASON";

export const GROUP_IMAGES_SHOW_SNACKBAR = "GROUP_IMAGES_SHOW_SNACKBAR";
export const GROUP_IMAGES_CLOSE_SNACKBAR = "GROUP_IMAGES_CLOSE_SNACKBAR";

export const GROUP_IMAGES_SHOW_CANVAS = "GROUP_IMAGES_SHOW_CANVAS";
export const GROUP_IMAGES_HIDE_CANVAS = "GROUP_IMAGES_HIDE_CANVAS";

export const GROUP_IMAGES_CHANGE_BARCODE = "GROUP_IMAGES_CHANGE_BARCODE";

export const GROUP_IMAGES_VALID = "GROUP_IMAGES_VALID";
export const GROUP_IMAGES_SAVING = "GROUP_IMAGES_SAVING";
export const GROUP_IMAGES_SAVE_SUCCESS = "GROUP_IMAGES_SAVE_SUCCESS";
export const GROUP_IMAGES_SAVE_ERROR = "GROUP_IMAGES_SAVE_ERROR";

export const GROUP_IMAGES_RESET_STATE = "GROUP_IMAGES_RESET_STATE";
