export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

export const FETCHING_DATA = 'FETCHING_DATA';
export const RECIEVE_DATA = 'RECIEVE_DATA';
export const DID_VALIDATION = 'DID_VALIDATION';


export default {
    OPEN_DIALOG,
    CLOSE_DIALOG,
    FETCHING_DATA,
    RECIEVE_DATA,
    DID_VALIDATION,
}
