/**
 * LAYOUT DEFINITIONS
 */
export const INVOICE_RECEIVE_LAYOUT_DEFINITION =
  'INVOICE_RECEIVE_LAYOUT_DEFINITION';
export const INVOICE_REQUEST_LAYOUT_DEFINITION =
  'INVOICE_REQUEST_LAYOUT_DEFINITION';

/**
 * TASK
 */
export const INVOICE_CLOSE_WARNING_LIST = 'INVOICE_CLOSE_WARNING_LIST';
export const INVOICE_DONE_CLAIM_TASK = 'INVOICE_DONE_CLAIM_TASK';
export const INVOICE_DONE_CLAIM_TASK_ERROR = 'INVOICE_DONE_CLAIM_TASK_ERROR';
export const INVOICE_DONE_SAVE_TASK = 'INVOICE_DONE_SAVE_TASK';
export const INVOICE_OPEN_WARNING_LIST = 'INVOICE_OPEN_WARNING_LIST';
export const INVOICE_REQUEST_CLAIM_TASK = 'INVOICE_REQUEST_CLAIM_TASK';
export const INVOICE_SAVING_TASK = 'INVOICE_SAVING_TASK';
export const INVOICE_UPDATE_GET_NEXT_TASK = 'INVOICE_UPDATE_GET_NEXT_TASK';

/**
 * DOCUMENT
 */
export const INVOICE_CHANGE_TEXTAREA_MODE = 'INVOICE_CHANGE_TEXTAREA_MODE';
export const INVOICE_RECIEVE_DOCUMENT_DATA = 'INVOICE_RECIEVE_DOCUMENT_DATA';
export const INVOICE_UPDATE_ANCHOREL = 'INVOICE_UPDATE_ANCHOREL';
export const INVOICE_UPDATE_DOCUMENT_DATA = 'INVOICE_UPDATE_DOCUMENT_DATA';
export const INVOICE_UPDATE_FOCUS_DETAILS = 'INVOICE_UPDATE_FOCUS_DETAILS';

/**
 *
 */
export const ROUTE_INVOICE = 'invoice';
/**
 * ERROR
 */
export const INVOICE_UPDATE_ERROR = 'INVOICE_UPDATE_ERROR';
/**
 * IMAGE
 */

export const INVOICE_RECIEVE_IMAGE_URI = 'INVOICE_RECIEVE_IMAGE_URI';
export const INVOICE_SELECT_IMAGE = 'INVOICE_SELECT_IMAGE';
export const INVOICE_UPDATE_POSITION = 'INVOICE_UPDATE_POSITION';

/**
 * RESET STATE
 */
export const INVOICE_DOCUMENT_RESET_STATE = 'INVOICE_DOCUMENT_RESET_STATE';
export const INVOICE_ERROR_RESET_STATE = 'INVOICE_ERROR_RESET_STATE';
export const INVOICE_IMAGE_RESET_STATE = 'INVOICE_IMAGE_RESET_STATE';
export const INVOICE_RESET_LAYOUT_DEFINITION =
  'INVOICE_RESET_LAYOUT_DEFINITION';
export const INVOICE_TASK_RESET_STATE = 'INVOICE_TASK_RESET_STATE';

/**
 * KEY TASK ATTRIBUTE WORKFLOW
 */
export const KEY_COMPLETE_OPTION = 'complete_option';
export const KEY_KEYING_DATA = 'key_datas';
export const KEY_COMMENT = 'comment';
export const KEY_HOLD_COUNT = 'hold_count';
export const KEY_FORM_URI = 'form_uri';

/**
 * KEY ACTION INVOICE
 */
export const KEY_ACTION_KEYING = 'keying';
export const KEY_ACTION_PROOF = 'proof';
export const KEY_ACTION_QC = 'qc';

/**
 * KEY DIALOG DETAIL TYPE
 */
export const KEY_COMMENT_DIALOG = 'comment';
export const KEY_WORKING_DETAIL_DIALOG = 'working_detail';
export const KEY_SHORTCUT_DIALOG = 'shortcut';
export const KEY_SELF_COMMENT_DIALOG = 'self_comment';

export const INVOICE_OPEN_DETAIL_DIALOG = 'INVOICE_OPEN_DETAIL_DIALOG';
export const INVOICE_CLOSE_DETAIL_DIALOG = 'INVOICE_CLOSE_DETAIL_DIALOG';
