/**
 * ROUTE 
 */
export const ROUTE_VERIFY_KEY = 'verifying/key';
/**
 * FIELDS DEFINITION
 */

export const VERIFY_KEY_REQUEST_FIELDS_DEFINITION =
  'VERIFY_KEY_REQUEST_FIELDS_DEFINITION';
export const VERIFY_KEY_RECIEVE_FIELDS_DEFINITION =
  'VERIFY_KEY_RECIEVE_FIELDS_DEFINITION';
export const VERIFY_KEY_RESET_STATE_FIELDS_DEFINITION =
  'VERIFY_KEY_RESET_STATE_FIELDS_DEFINITION';

export const VERIFY_KEY_DONE_GET_FIELDS_DEFINITION =
  'VERIFY_KEY_DONE_GET_FIELDS_DEFINITION';
export const VERIFY_KEY_REQUEST_TASK = 'VERIFY_KEY_REQUEST_TASK';
export const VERIFY_KEY_RECIEVE_TASK = 'VERIFY_KEY_RECIEVE_TASK';
export const VERIFY_KEY_SAVING_TASK = 'VERIFY_KEY_SAVING_TASK';
export const VERIFY_KEY_SAVED_SUCCESS_TASK = 'VERIFY_KEY_SAVED_SUCCESS_TASK';
export const VERIFY_KEY_UPDATE_NEXT_TASK = 'VERIFY_KEY_UPDATE_NEXT_TASK';
export const VERIFY_KEY_RESET_STATE = 'VERIFY_KEY_RESET_STATE';

export const VERIFY_KEY_SET_FOCUS_RECORD = 'VERIFY_KEY_SET_FOCUS_RECORD';
export const VERIFY_KEY_SET_FOCUS_FIELD = 'VERIFY_KEY_SET_FOCUS_FIELD';

export const VERIFY_KEY_RESET_STATE_DATA = 'VERIFY_KEY_RESET_STATE_DATA';
export const VERIFY_KEY_MODIFY_FINAL_DATA = 'VERIFY_KEY_MODIFY_FINAL_DATA';
export const VERIFY_KEY_UPDATE_ERROR_DOCUMENT =
  'VERIFY_KEY_UPDATE_ERROR_DOCUMENT';
