export const CALL_AJAX_REQUSEST = "CALL_AJAX_REQUSEST";
export const CALL_AJAX_RESPONSE = "CALL_AJAX_RESPONSE";
export const CALL_AJAX_ERROR = "CALL_AJAX_ERROR";
export const CALL_AJAX_CLOSE_SNACKBAR = "CALL_AJAX_CLOSE_SNACKBAR";
