/**
 * AJAX ACTION DEFINITION
 */

export const COMMON_SEND_HTTP_REQUEST = 'COMMON_SEND_HTTP_REQUEST';
export const COMMON_RECEIVE_HTTP_RESPONSE = 'COMMON_RECEIVE_HTTP_RESPONSE';
export const COMMON_RESPOND_OPEN_SNACKBAR = 'COMMON_RESPOND_OPEN_SNACKBAR';
export const COMMON_REQUEST_OPEN_SNACKBAR = 'COMMON_REQUEST_OPEN_SNACKBAR';
export const COMMON_CLOSE_SNACKBAR = 'COMMON_CLOSE_SNACKBAR';
