export const TYPE_DRAG = 'drag';
export const TYPE_DRAW = 'draw';

export const BoxCornerSize = 12;

export const CANVAS_DRAW_INIT = 'CANVAS_DRAW_INIT';
export const CANVAS_DRAW_RESET = 'CANVAS_DRAW_RESET';
export const CANVAS_DRAW_ADD_SHAPE = 'CANVAS_DRAW_ADD_SHAPE';
export const CANVAS_DRAW_CHANGE_TYPE = 'CANVAS_DRAW_CHANGE_TYPE';
export const CANVAS_DRAW_DELETE_SHAPE = 'CANVAS_DRAW_DELETE_SHAPE';
export const CANVAS_DRAW_SELECT_SHAPE = 'CANVAS_DRAW_SELECT_SHAPE';
export const CANVAS_DRAW_SET_DRAGGING = 'CANVAS_DRAW_SET_DRAGGING';

export const CANVAS_DRAW_REFRESH = 'CANVAS_DRAW_REFRESH';
