/**
 * Classify
 */

export const CLASSIFY_MULTIPLE_CHANGE_DISPLAY_TYPE = "CLASSIFY_MULTIPLE_CHANGE_DISPLAY_TYPE";
export const CLASSIFY_MULTIPLE_GET_DONE_DATA_DEFINITION = "CLASSIFY_MULTIPLE_GET_DONE_DATA_DEFINITION";
export const CLASSIFY_REQUEST_MULTIPLE_TASK = "CLASSIFY_REQUEST_MULTIPLE_TASK";
export const CLASSIFY_RESPONSE_MULTIPLE_TASK = "CLASSIFY_RESPONSE_MULTIPLE_TASK";
export const CLASSIFY_MULTIPLE_SELECT_LAYOUT_DEFINITION = "CLASSIFY_MULTIPLE_SELECT_LAYOUT_DEFINITION";
export const CLASSIFY_RESET_STATE_MULTIPLE_TASK_CLASSIFY = "CLASSIFY_RESET_STATE_MULTIPLE_TASK_CLASSIFY";
export const CLASSIFY_SHOW_CANVAS = "CLASSIFY_SHOW_CANVAS";
export const CLASSIFY_HIDE_CANVAS = "CLASSIFY_HIDE_CANVAS";
export const CLASSIFY_MULTIPLE_SELECT_INDEX_DOCUMENT = "CLASSIFY_MULTIPLE_SELECT_INDEX_DOCUMENT";
export const CLASSIFY_SAVING_MULTIPLE_TASK = "CLASSIFY_SAVING_MULTIPLE_TASK";
export const CLASSIFY_SAVED_SUCCESS_MULTIPLE_TASK = "CLASSIFY_SAVED_SUCCESS_MULTIPLE_TASK";
export const CLASSIFY_SAVED_ERROR_MULTIPLE_TASK = "CLASSIFY_SAVED_ERROR_MULTIPLE_TASK";
export const CLASSIFY_MULTIPLE_SHOW_SNACKBAR = "CLASSIFY_MULTIPLE_SHOW_SNACKBAR";
export const CLASSIFY_MULTIPLE_CLOSE_SNACKBAR = "CLASSIFY_MULTIPLE_CLOSE_SNACKBAR";
export const CLASSIFY_MULTIPLE_UPDATE_NEXT_TASK = "CLASSIFY_MULTIPLE_UPDATE_NEXT_TASK";


export const CLASSIFY_SINGLE_UPDATE_NEXT_TASK = "CLASSIFY_SINGLE_UPDATE_NEXT_TASK";
export const CLASSIFY_SINGLE_GET_DONE_DATA_DEFINITION = "CLASSIFY_SINGLE_GET_DONE_DATA_DEFINITION";
export const CLASSIFY_RESPONSE_SINGLE_TASK = "CLASSIFY_RESPONSE_SINGLE_TASK";
export const CLASSIFY_REQUEST_SINGLE_TASK = "CLASSIFY_REQUEST_SINGLE_TASK";
export const CLASSIFY_SINGLE_SHOW_SNACKBAR = "CLASSIFY_SINGLE_SHOW_SNACKBAR";
export const CLASSIFY_SINGLE_CLOSE_SNACKBAR = "CLASSIFY_SINGLE_CLOSE_SNACKBAR";
export const CLASSIFY_SINGLE_SELECT_LAYOUT_DEFINITION = "CLASSIFY_SINGLE_SELECT_LAYOUT_DEFINITION";
export const CLASSIFY_SINGLE_SELECT_INDEX_DOCUMENT = "CLASSIFY_SINGLE_SELECT_INDEX_DOCUMENT";
export const CLASSIFY_RESET_STATE_TASK_CLASSIFY = "CLASSIFY_RESET_STATE_TASK_CLASSIFY";
export const CLASSIFY_SAVING_SINGLE_TASK = "CLASSIFY_SAVING_SINGLE_TASK";
export const CLASSIFY_SAVED_SUCCESS_SINGLE_TASK = "CLASSIFY_SAVED_SUCCESS_SINGLE_TASK";
export const CLASSIFY_SAVED_ERROR_SINGLE_TASK = "CLASSIFY_SAVED_ERROR_SINGLE_TASK";

export const CLASSIFY_VERIFY_CHANGE_APPROVED = "CLASSIFY_VERIFY_CHANGE_APPROVED"
export const CLASSIFY_VERIFY_UPDATE_NEXT_TASK = "CLASSIFY_VERIFY_UPDATE_NEXT_TASK"
export const  CLASSIFY_VERIFY_CHANGE_DISPLAY_TYPE = "CLASSIFY_VERIFY_CHANGE_DISPLAY_TYPE"
export const  CLASSIFY_VERIFY_GET_DONE_DATA_DEFINITION = "CLASSIFY_VERIFY_GET_DONE_DATA_DEFINITION"
export const  CLASSIFY_VERIFY_SELECT_INDEX_DOCUMENT = "CLASSIFY_VERIFY_SELECT_INDEX_DOCUMENT"
export const   CLASSIFY_REQUEST_VERIFY_TASK = "CLASSIFY_REQUEST_VERIFY_TASK"
export const   CLASSIFY_RESPONSE_VERIFY_TASK = "CLASSIFY_RESPONSE_VERIFY_TASK"
export const   CLASSIFY_VERIFY_SHOW_SNACKBAR = "CLASSIFY_VERIFY_SHOW_SNACKBAR"
export const   CLASSIFY_VERIFY_CLOSE_SNACKBAR = "CLASSIFY_VERIFY_CLOSE_SNACKBAR"
export const  CLASSIFY_RESET_STATE_VERIFY_TASK_CLASSIFY = "CLASSIFY_RESET_STATE_VERIFY_TASK_CLASSIFY"
export const   CLASSIFY_SAVING_VERIFY_TASK = "CLASSIFY_SAVING_VERIFY_TASK"
export const  CLASSIFY_VERIFY_SELECT_LAYOUT_DEFINITION = "CLASSIFY_VERIFY_SELECT_LAYOUT_DEFINITION"
export const  CLASSIFY_SAVED_ERROR_VERIFY_TASK = "CLASSIFY_SAVED_ERROR_VERIFY_TASK"
export const  CLASSIFY_SAVED_SUCCESS_VERIFY_TASK = "CLASSIFY_SAVED_SUCCESS_VERIFY_TASK"

/**
 * Layout definitions
 */
export const CLASSIFY_RESET_STATE_LAYOUT_DEFINITION = "CLASSIFY_RESET_STATE_LAYOUT_DEFINITION";
export const CLASSIFY_SET_TEXT_SEARCH_LAYOUT_DEFINITIONS = "CLASSIFY_SET_TEXT_SEARCH_LAYOUT_DEFINITIONS";
export const CLASSIFY_REQUEST_LAYOUT_DEFINITIONS = "CLASSIFY_GET_LAYOUT_DEFINITIONS";
export const CLASSIFY_RESPONSE_LAYOUT_DEFINITIONS = "CLASSIFY_RESPONSE_LAYOUT_DEFINITIONS";
export const CLASSIFY_ERROR_LAYOUT_DEFINITIONS = "CLASSIFY_ERROR_LAYOUT_DEFINITIONS";
